New germplasm accession importer
UofS-Pulse-Binfo/tripal_germplasm_importer pull request #14
Opened 2019-07-04 21:07 UTC by Jiu9Shen

2019-07-04 21:18 UTC, Jiu9Shen commented
Need to finish PHP UnitTest, but it can load accession files now. 
Tested on tripal, local KP and KP2/fresh alreay.

2019-10-22 17:01 UTC, laceysanderson requested changes
Ran the importer with your provided test file and recieved 2X the germplasm...
![Screen Shot 2019-10-22 at 10 57 37 AM](https://user-images.githubusercontent.com/1566301/67310417-f0a5c180-f4ba-11e9-823a-69f93300e599.png)

```
$ drush trp-run-jobs --username=tripaladmin --root=/Users/laceysanderson/Sites/tripal-TEST

2019-10-22 11:51:25
Tripal Job Launcher
Running as user 'tripaladmin'
-------------------
2019-10-22 11:51:25: There are 1 jobs queued.
2019-10-22 11:51:25: Job ID 12.
2019-10-22 11:51:25: Calling: tripal_run_importer(9)

Running 'Germplasm Accession Importer' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

Upload file name: germplasm_accession_test1.tsv 
WARNING: The db, KnowPulse, has no match in chado:db.
WARNING: The db, ICARDA, has no match in chado:db.es.

Done.

Remapping Chado Controlled vocabularies to Tripal Terms...
Done.
Kirstins-Air:tripal_germplasm_importer laceysanderson$ drush trp-run-jobs --username=tripaladmin --root=/Users/laceysanderson/Sites/tripal-TEST

2019-10-22 11:52:03
Tripal Job Launcher
Running as user 'tripaladmin'
-------------------
2019-10-22 11:52:03: There are 1 jobs queued.
2019-10-22 11:52:03: Job ID 13.
2019-10-22 11:52:03: Calling: chado_publish_records(Array)
INFO (PUBLISH_RECORDS): There are 4 records to publish.
There are 4 records to publish.
INFO (PUBLISH_RECORDS): Successfully published 4 Germplasm Accession record(s).
Successfully published 4 Germplasm Accession record(s).
```
When I checked the published germplasm, they were perfect duplicates with both having the properties loaded in.
![Screen Shot 2019-10-22 at 11 01 02 AM](https://user-images.githubusercontent.com/1566301/67310580-48dcc380-f4bb-11e9-8218-ae08d0dc7f39.png)

2019-10-29 16:10 UTC, laceysanderson approved these changes
Functionality works now 👍 Documentation is sufficient with one small suggested change. Thanks for the new importer @Jiu9Shen!

2019-10-29 16:10 UTC, laceysanderson commented on docs/features/germplasm_accession_importer.rst
> +  For column 13 (Synonyms), multiple synonyms are allowed but must be separated by pounctuation marks. Like, ``syn1;syn2;syn3``.
```suggestion
  For column 13 (Synonyms), multiple synonyms are allowed but must be separated by semi-colons (e.g.  ``syn1;syn2;syn3``).
```

2019-10-29 16:27 UTC, merged